---
- name: Deploy do Zabbix Agent2
  hosts: "{{ grupo }}"
  become: true
  vars:
    - zabbix_release_version: 6.0
  
  roles:
    - zabbix.agent2

  post_tasks:
    - include_role:
        name: zabbix.agent2
        tasks_from: setup.yml