---
- name: "Liberando ping"
  hosts: win_vms_ti	
  tasks:	
  - name: "Aplicando"
    ansible.windows.win_command: 'netsh advfirewall firewall add rule name="ICMP Allow incoming V4 echo request" protocol="icmpv4:8,any" dir=in action=allow'

