  - name: Desabilitando Selinux
    selinux:
     state: disabled

  - name: 'Baixando o pacote do Zabbix {{ zabbix_release_version }} | Sistema Operacional: {{ansible_distribution}} - 8'
    dnf:
      disable_gpg_check: yes
      name: 'https://repo.zabbix.com/zabbix/{{ zabbix_release_version }}/rhel/{{ansible_distribution_major_version}}/x86_64/zabbix-release-{{ zabbix_release_version }}-1.el8.noarch.rpm'
      state: present
    when: ansible_distribution_major_version == '8'  

  - name: 'Instalando Zabbix Proxy | Sistema Operacional: {{ansible_distribution}} - 8'
    dnf:
     name: 
        - zabbix-proxy
        - zabbix-get
        - zabbix-sender
     enablerepo: zabbix
     update_cache: true
     state: latest
    when: ansible_distribution_major_version == '8'

  - name: Reiniciando o firewalld
    systemd:
      name: firewalld
      state: reloaded
      enabled: yes 