---
##--Verificando o OS do host--##
- name: ping hosts
  ping:

- name: check OS
  debug: msg={{ansible_os_family}}-{{ansible_distribution}}-{{ansible_distribution_major_version}}

##--Rhel8--##
- name: Desabilitando o SELinux
  selinux:
    state: disabled
  when: ansible_os_family == "RedHat"

- name: Instalando o pacote do zabbix no {{ansible_distribution}}-{{ansible_distribution_major_version}}
  dnf:
    disable_gpg_check: yes
    name: "{{ rhel8_link }}"
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version== "8"

- name: Instalando Zabbix Agent 2 no {{ansible_distribution}}-{{ansible_distribution_major_version}}
  dnf:
    name: zabbix-agent
    enablerepo: zabbix
    update_cache: true
    state: latest
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version== "8"
